# 启用所有观测功能
spring:
  application:
    name: seata-account
  datasource:
    url: jdbc:mysql://192.168.1.242:3306/account_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: bubua12
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.1.242:8848
      username: nacos
      password: nacos
      config:
        import-check:
          enabled: false
server:
  port: 20001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启MyBatis SQL日志
#seata:
#  data-source-proxy-mode: XA

logging:
  level:
    com.bubua12.cloud.account.mapper: DEBUG


otel:
  propagators:
    - tracecontext
    - baggage