spring:
  profiles:
    include: feign,sentinel
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
  application:
    name: service-order
  cloud:
    nacos:
      config:
        namespace: 1a66b752-f1f1-422a-8a33-b8d7327f9aa5
      server-addr: 192.168.1.242:8848
      username: nacos
      password: nacos


otel:
  propagators:
    - tracecontext
    - baggage

server:
  port: 8024

# 开启feign包下的debug级别日志
logging:
  level:
    com.bubua12.cloud.order.feign: debug
    org.springframework.cloud.openfeign: debug
    feign.Logger: debug