spring:
  application:
    name: seata-order
  datasource:
    url: jdbc:otel:mysql://192.168.1.242:3306/order_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: bubua12
    driver-class-name: io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver
  cloud:
    nacos:
      server-addr: 192.168.1.242:8848
      username: nacos
      password: nacos
      config:
        import-check:
          enabled: false

server:
  port: 22000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启MyBatis SQL日志

management:
  otlp:
    metrics:
      export:
        enabled: true
    tracing:
      endpoint: http://192.168.1.242:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0 # 采样率100%