spring:
  profiles:
    include: route # 包含路由配置文件
  application:
    name: ms-gateway
  cloud:
    nacos:
      server-addr: ${NACOS_URL:http://127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        metadata:
          env: ${ENV:dev}
          version: 1.1.2-${ENV:dev}

server:
  port: 3333

management:
  tracing:
    enabled: true
    propagation:
      type: W3C

otel:
  service:
    name: bubua12-${spring.application.name}
  propagators: tracecontext,baggage
  resource:
    attributes:
      deployment:
        environment: prod
      service:
        namespace: ms.microservices

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}] %logger{36} - %msg%n'