spring:
  cloud:
    gateway:
      routes: # 从上到下依次匹配、但是还可以使用order配置优先级(数字越小，优先级越高)
        - id: order-route # 路由的名字
          uri: lb://service-order # 转给哪个服务，这里负载均衡到订单服务
          predicates: # 断言，又是一个list
            - Path=/api/order/** # 路径规则
          filters:
            - RewritePath=/api/order/?(?<segment>.*), /$\{segment}
            - AddResponseHeader=X-Response, bubua12

        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**

        - id: warehouse-route
          uri: lb://service-warehouse
          predicates:
            - name: Path
              args:
                patterns: /api/warehouse/**
                matchTrailingSlash: true

        - id: bing-route
          uri: https://cn.bing.com/
          predicates: # 多个断言时，必须全部匹配才可以路由到
            - name: Path
              args:
                patterns: /search
            - name: Query
              args:
                param: q
                regexp: haha
            - name: Vip
              args: # 这里是条件，必须是如下的条件才行
                param: user
                value: wangbubu

      default-filters:
        - AddResponseHeader=X-Wang, bubua12