version: '3.8'

services:
  app:
    image: image
    container_name: container_name
    environment:
      - ENV=prod
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:4318
      - NACOS_URL=127.0.0.1:8848
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=nacos
      - JAVA_OPTS=-server -XX:+UseG1GC -XX:G1HeapRegionSize=8 -XX:MaxGCPauseMillis=500 -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+UseContainerSupport -Xms1g -Xmx3g -XX:MetaspaceSize=128m
      - SERVER_TYPE=tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/bubua12/logs
    restart: always
