spring:
  application:
    name: seata-business
  cloud:
    nacos:
      server-addr: 192.168.1.242:8848
      username: nacos
      password: nacos
      config:
        import-check:
          enabled: false
server:
  port: 21000

otel:
  service:
    name: otel-${spring.application.name}
  resource:
    attributes:
      deployment:
        environment: prod
      service:
        namespace: ms.microservices
  exporter:
    otlp:
      traces:
        endpoint: http://192.168.1.242:4318/v1/traces
      protocol: http/protobuf

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}] %logger{36} - %msg%n'
