spring:
  application:
    name: seata-business
  cloud:
    nacos:
      server-addr: ${NACOS_URL:http://127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      config:
        import-check:
          enabled: false
server:
  port: 21000

otel:
  service:
    name: bubua12-${spring.application.name}
  propagators: tracecontext,baggage
  resource:
    attributes:
      deployment:
        environment: prod
      service:
        namespace: ms.microservices

management:
  tracing:
    enabled: true
    propagation:
      type: W3C

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}] %logger{36} - %msg%n'
