spring:
  application:
    name: seata-business
  cloud:
    nacos:
      server-addr: 192.168.1.242:8848
      username: nacos
      password: nacos
      config:
        import-check:
          enabled: false
server:
  port: 21000

management:
  otlp:
    tracing:
      endpoint: http://192.168.1.242:4318/v1/traces
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # 采样率100%
  endpoints:
    web:
      exposure:
        include: health,info,metrics,tracing
# 开启链路追踪日志 - 修复日志中traceId显示问题
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    io.micrometer.tracing: DEBUG
    io.opentelemetry: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'